// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://peitasmlqqbmfwpzwjis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlaXRhc21scXFibWZ3cHp3amlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NDgxNTIsImV4cCI6MjA4ODAyNDE1Mn0.FmRDnu-E5A07zPL3olUuRpq2QSbILqShVteqtboCBUs";

console.log("Supabase URL (Configurada Direta):", SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});